language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
  - git clone https://github.com/amattioc/SDMX.git ~/builds/sdmx
  - pushd ~/builds/sdmx/JAVA
  - mvn clean install -DskipTests=true
  - popd
script: cd demetra-dotstat && mvn clean install && cd ../nbdemetra-dotstat && mvn clean install
